### ISSUE TITLE
Request open source the projector weights

### ISSUE THREAD

**Issue by lsnls** [ddw2AIGROUP2CQUPT/PA-LLaVA#5]
Hello, authors!

Thanks for your valuable work! I am trying to run `zero_shot.py` on my own dataset using the `PA-LLaVA` checkpoint. Could you please clarify which checkpoint the `--llava ./instruction_tuning_weight_ft` parameter corresponds to? I have tried all the open-sourced weights on Huggingface, but none match. Can you also open source the projector weight?

Thanks for your help and response!

Best regards,
Suoni

**Comment by lsnls** [comment]
@ddw2AIGROUP2CQUPT

**Comment by ddw2AIGROUP2CQUPT** [comment]
Thank you for your interest. In fact, we have already released the weights and provided instructions in the README.md. Based on your question, it seems that you need to merge the weights into the required format. The instructions for doing so are available on Hugging Face.

**Comment by lsnls** [comment]
Hello, @ddw2AIGROUP2CQUPT , thank you so much for your quick response!

Following the instructions on Hugging Face, I ran the command `xtuner convert pth_to_hf pallava_instruction_tuning.py path_to/instruction_tuning_weight_ft.pth path_to/instruction_tuning_weight_ft`. However, I encountered an error: `TypeError: LLaVAModel.__init__() got an unexpected keyword argument 'projector_type'`. Could you please assist me in resolving this issue?

Thank you again!

**Comment by ddw2AIGROUP2CQUPT** [comment]
Thank you for your questions and we have made the necessary corrections to our files.

**Comment by aruiplex** [comment]
Hi @ddw2AIGROUP2CQUPT, I still meet this issue, 
```
Traceback (most recent call last):
  File "/data/Hypothesis/proposition/Pathology-LLaVA/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 151, in <module>
    main()
  File "/data/Hypothesis/proposition/Pathology-LLaVA/xtuner/xtuner/tools/model_converters/pth_to_hf.py", line 105, in main
    model = BUILDER.build(cfg.model)
  File "/data/Hypothesis/domain/medical/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data/Hypothesis/domain/medical/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 123, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'projector_type'
```

How can I solve this? Thanks!
