### ISSUE TITLE
KeyError: 'Adafactor is already registered in optimizer at torch.optim'

### ISSUE THREAD

**Issue by barisuzar** [ddw2AIGROUP2CQUPT/PA-LLaVA#6]
Hi, I am getting _"KeyError: 'Adafactor is already registered in optimizer at torch.optim'"_ error while performing the conversion ( pth_to_hf) using the following command:

> "xtuner convert pth_to_hf path/pallava_domain_alignment.py ./domain_alignment_weight.pth ./domain_alignment_weight_ft"

The Python version I'm currently using is 3.10.11

You can see some of the installed packages at the bottom.

```
(xtuner-env) D:\xtuner-env>xtuner convert pth_to_hf pallava_domain_alignment.py domain_alignment_weight.pth domain_alignment_weight_ft
D:\xtuner-env\lib\site-packages\mmengine\optim\optimizer\zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
[2024-11-13 13:52:37,472] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
D:\xtuner-env\lib\site-packages\deepspeed\runtime\zero\linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
D:\xtuner-env\lib\site-packages\deepspeed\runtime\zero\linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
W1113 13:52:37.870000 3212 torch\distributed\elastic\multiprocessing\redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "D:\xtuner-env\lib\site-packages\xtuner\tools\model_converters\pth_to_hf.py", line 16, in <module>
    from xtuner.model.utils import guess_load_checkpoint
  File "D:\Python\lib\site-packages\xtuner\model\__init__.py", line 2, in <module>
    from .internvl import InternVL_V1_5
  File "D:\Python\lib\site-packages\xtuner\model\internvl.py", line 8, in <module>
    from mmengine.model import BaseModel
  File "D:\Python\lib\site-packages\mmengine\model\__init__.py", line 6, in <module>
    from .base_model import BaseDataPreprocessor, BaseModel, ImgDataPreprocessor
  File "D:\Python\lib\site-packages\mmengine\model\base_model\__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "D:\Python\lib\site-packages\mmengine\model\base_model\base_model.py", line 9, in <module>
    from mmengine.optim import OptimWrapper
  File "D:\Python\lib\site-packages\mmengine\optim\__init__.py", line 2, in <module>
    from .optimizer import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "D:\Python\lib\site-packages\mmengine\optim\optimizer\__init__.py", line 5, in <module>
    from .builder import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "D:\Python\lib\site-packages\mmengine\optim\optimizer\builder.py", line 174, in <module>
    TRANSFORMERS_OPTIMIZERS = register_transformers_optimizers()
  File "D:\Python\lib\site-packages\mmengine\optim\optimizer\builder.py", line 169, in register_transformers_optimizers
    OPTIMIZERS.register_module(name='Adafactor', module=Adafactor)
  File "D:\Python\lib\site-packages\mmengine\registry\registry.py", line 661, in register_module
    self._register_module(module=module, module_name=name, force=force)
  File "D:\Python\lib\site-packages\mmengine\registry\registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'Adafactor is already registered in optimizer at torch.optim'
```
----------------------------- --------------
**Libs used:** 

accelerate                    1.1.1
datasets                      3.1.0
deepspeed                     0.11.2+unknown
huggingface-hub               0.26.2
mmcv                          2.1.0
mmdet                         3.3.0
mmengine                      0.10.5
opencv-python                 4.10.0.84
openmim                       0.3.9
referencing                   0.35.1
torch                         2.4.1+cu118
torchaudio                    2.4.1+cu118
torchvision                   0.19.1+cu118
tqdm                          4.65.2
transformers                  4.42.4
wheel                         0.45.0
xtuner                        0.1.23

**Comment by hahalonghaha** [comment]
Hi there,
I meet this problem too. Did you deal with it?
